version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.22.0
    ports:
      - '16686:16686'
      - '14268:14268'
      - '14250'

  proxy:
    image: traefik:v2.6
    ports:
      # The HTTP port
      - '80:80'
      # The Web UI (enabled by --api.insecure=true)
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '$PWD/traefik.yaml:/etc/traefik/traefik.yaml'

  redis:
    image: bitnami/redis:6.2
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=password

    labels:
      - 'traefik.http.routers.whoami.rule=Host(`redis.docker.localhost`)'
      - 'traefik.http.routers.whoami.entrypoints=http'
      - 'traefik.http.routers.whoami.entrypoints=web'

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - 'traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)'
      - 'traefik.http.routers.whoami.entrypoints=http'
      - 'traefik.http.routers.whoami.entrypoints=web'

  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    labels:
      - 'traefik.http.routers.whoami.rule=Host(`next.docker.localhost`)'
      - 'traefik.http.routers.whoami.entrypoints=http'
      - 'traefik.http.routers.whoami.entrypoints=web'
    volumes:
      - ./frontend:/app/
      - /app/node_modules
      - /app/.next
