log:
  level: warn

api:
  dashboard: true
  debug: false

entryPoints:
  http:
    address: ':80'
  https:
    address: ':443'

providers:
  docker:
    endpoint: 'tcp://socket-proxy:2375'
    watch: true
    exposedbydefault: false
# certificatesResolvers:
#   http:
#     acme:
#       email: amadeus@mozart409.com
#       storage: acme.json
#       httpChallenge:
#         entryPoint: http
#
# http:
#   middlewares:
#     https-redirect:
#       redirectScheme:
#         scheme: https
